---

- name: GRAFANA | Copy configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/grafana/{{ item }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
  notify: restart grafana
  with_items:
    - grafana.ini
