---

- hosts: grafana
  pre_tasks:
    - name: GRAFANA | Installing test dependencies
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - net-tools
  roles:
    - mysql
    - grafana_role
